### ISSUE TITLE
SQLite Errors on running .migrate()

### ISSUE THREAD

**Issue by Andrewwelton** [lecaillon/Evolve#15]
I'm using Evolve through the InApp configurations. When I run Evolve.migrate(), some SQLite errors are produced. 

`SQLite error (1): near "SHOW": syntax error`
`SQLite error (1): no such function: version`
`SQLite error (1): unrecognized token: "@"`

These don't actually impact the functionality of the migration tool. It works well. However as I add more migrations, each of the aforementioned errors gets repeated. So if I have 3 migrations, I get each of those errors 3 times. 
****EDIT**: The repeating must have been an error on my implementation, the errors do not stack as I introduce more migrations **

This happens with SQLite databases. I'm using System.Data.SQLite 1.0.99.0, Evolve version 1.5.1.
It can be reproduced without a migration to apply either, so I imagine it has something to do with the metadata collection.

**Comment by lecaillon** [comment]
Well, I reproduced partially your issue. I saw in the output window the SQLite error you mentioned.
But not 3 times for each migration scripts. Only 3 times by migration. Do you run `Evolve.Migrate()` multiples times ?

**Comment by Andrewwelton** [comment]
Apologies, I must've had something else going on to have it happen multiple times as I can't reproduce that part now. It is only the 3 for the whole migration.

**Comment by Andrewwelton** [comment]
That method was my best guess as to the cause of it. It was the only place I saw the "SHOW" sql query being used. Just seems weird if I'm providing the Driver when instantiating the class, shouldn't that be an indication?

As I mentioned, it definitely doesn't impact the performance of the framework (which is really fantastic by the way!), so if this isn't something that would be a simple fix feel free to close it :)

**Comment by lecaillon** [comment]
These messages are due to the [method](https://github.com/lecaillon/Evolve/blob/035138513fc8846769daf4ba748a17950b70d3f9/src/Evolve/Extensions/WrappedConnectionEx.cs#L14) I use to determine the database you use (SQL Server, SQLite, PostgreSQL ...)

I will try to use an another strategy in a future version, but honestly, because the migrations work fine 
it is not in my top priority list.

And yes, afterwards it's seems a bit awkward to guess what database you use that way... :pensive:

**Comment by Andrewwelton** [comment]
Totally fair! Thank you for the quick responses :)

**Comment by lecaillon** [comment]
@Andrewwelton I finally remember why I use this method to detect what type of DBMS is used. That's because Evolve can run in "App-Mode" (you instanciate the class `Evolve` in your code) and this way can be started with a DbConnection object in the constructor, without any driver specified. 

I don't know any method to determine wich kind of database is used with only a `IDbConnection`

Are you ? :wink:

**Comment by Andrewwelton** [comment]
Yeah that totally makes sense, I'm using the "App-Mode" myself :)

My thought was that if I instantiate the Evolve object in app like this: 
`var evolve = new Evolve.Evolve(connection, Console.WriteLine) { Driver = "sqlite" };`

I've provided what type of connection the `IDbConnection` is when I instantiated the `Evolve` object, so doing the extra work to try and figure it out seemed unnecessary.
