### ISSUE TITLE
Dry Runs feature support

### ISSUE THREAD

**Issue by olsh** [lecaillon/Evolve#160]
Flyway has [Dry Runs](https://flywaydb.org/documentation/dryruns) feature.
It would be beneficial to have the feature in Evolve too.

**Comment by lecaillon** [comment]
I'm currently working on a improved version of the `evolve info` command #123 where you can view the actual state of the database **and** determine migrations that need to be applied. 
I think it is a first good step to a feature like the dry run.

**Comment by lecaillon** [comment]
Finally, this feature will be available in Evolve 3.0 as an option : `TransactionMode.RollbackAll`.
The idea is to give the possibility to manage Evolve transaction scope. In this case, run all the scripts of the migration and then rollback them in order to validate/preview the changes Evolve will make to the database.

**Comment by lecaillon** [comment]
See #210 for the `TransactionMode.CommitAll` feature
I will publish soon **Evolve 3.0.0-alpha5** to be able to test it before I release it. Feel free to give feedback
