### ISSUE TITLE
Placeholders not working

### ISSUE THREAD

**Issue by Bolt54** [lecaillon/Evolve#171]
I'm trying to run Evolve via the cli against a Postgres database with placeholders.  The placeholders were not setup with a prefix or suffix.  This works when running on startup from my WebAPI project, but I can't get to work from the cli.

**Comment by Bolt54** [comment]
evolve migrate postgresql --scripts-suffix .psql --placeholder-prefix "" --placeholder-suffix "" -c "…" -l "…" -p DbAppGroup:value -p DbMigrationUser:value

**Comment by lecaillon** [comment]
Hi @Bolt54 

I do not reproduce your issue on my database with the CLI and options --placeholder-prefix "" --placeholder-suffix ""
For testing purpose, maybe you can try using the default placeholder prefix and suffix.

Below the command I executed successfully:
```sh
evolve migrate sqlite --connection-string="Data Source=C:\Users\lecai\Downloads\my_database.db" --location="C:\Projets\Evolve\test\Evolve.Tests\Integration\SQLite\Resources\Sql_Scripts\Migration" --placeholder-prefix "" --placeholder-suffix "" --placeholder XXX:table_4 --out-of-order=True
```

And the migration script:
```sql
CREATE TABLE XXX (
  id INT NOT NULL,
  name VARCHAR(10) NOT NULL,
  PRIMARY KEY(name)
);

CREATE TRIGGER update_XXX UPDATE OF name ON XXX
  BEGIN
    UPDATE XXX SET id = 100 WHERE name = old.name;
  END;
  
SELECT * FROM table_4;
```

**Comment by Corey91989** [comment]
I'm also having issues with placeholders, although I'm not sure if it's related since my issue is on app startup.

We have 2 separate databases that some of our stored procedures use, so I just want to pass those 2 database names into the executing scripts. However, it doesn't seem to be replacing the placeholder values. I've tried specifying the placeholders both in the web.config (as shown in the documentation) as well as directly on the Evolve object before calling Migrate. Is there something I'm doing wrong here?

![Placeholders_Issue](https://user-images.githubusercontent.com/2459083/74880897-43dd3300-533a-11ea-9f53-87ce34affa86.PNG)

**Comment by Corey91989** [comment]
I'm also having issues with placeholders, although I'm not sure if it's related since my issue is on app startup.

We have 2 separate databases that some of our stored procedures use, so I just want to pass those 2 database names into the executing scripts. However, it doesn't seem to be replacing the placeholder values. I've tried specifying the placeholders both in the web.config (as shown in the documentation) as well as directly on the Evolve object before calling Migrate. Is there something I'm doing wrong here?

![Placeholders_Issue](https://user-images.githubusercontent.com/2459083/74881988-4fc9f480-533c-11ea-9878-9d2d24ff2241.PNG)

**Comment by lecaillon** [comment]
You have to use the prefix and suffix in placeholder keys :
```c#
            var evolve = new Evolve(cnn, msg => _output.WriteLine(msg))
            {
                Placeholders = new Dictionary<string, string> { ["${db}"] = DbName, ["${schema2}"] = "dbo" },
                TargetVersion = new MigrationVersion("8_9"),
            };
```

**Comment by Bolt54** [comment]
@lecaillon Thanks for the feedback I will try to better reproduce.

Requiring the prefix and suffix in the placeholder keys seems a bit confusing based on the documentation.  I was under the impression that the defaults ${, } would always be concatenated to the keys.

**Comment by lecaillon** [comment]
@Bolt54 Can I close the issue ?

**Comment by Bolt54** [comment]
Yes, I was able to get it work locally now.  Thanks for the assistance.

**Comment by sjd2021** [comment]
What's the point of having "PlaceholderPrefix" default to "${" then?
