### ISSUE TITLE
Add validation command 

### ISSUE THREAD

**Issue by maslbl4** [lecaillon/Evolve#228]
Please add validate command as in other migration libraries.

This command must validate input migrations with already applied migrations and in case of a mismatch, throw an error

Links for libraries:
- **Flyway**
https://flywaydb.org/documentation/usage/commandline/validate
- **Liquibase**
https://docs.liquibase.com/commands/community/validate.html

**Comment by lecaillon** [comment]
When the validation must fail ?
- when we don't find the script of an already applied migration.
- when the checksum of the found script does not match the checksum of the applied migration.
- when a existing script is not applied yet ?

Not sure about the last one.
Do you see other reasons ?

**Comment by fredericbirke** [comment]
The last one is important as well. If your services don't automatically migrate the database (which is the case, if you have multiple instances of the same service), you still want to be able to report the service as unhealthy in this case, because the database doesn't meet the services requirements.

**Comment by lecaillon** [comment]
@maslbl4 @fredericbirke Finally done in #241 

New feature available in `Evolve 3.1.0-alpha2`
