### ISSUE TITLE
Relation "changelog" already exists Sql query: CREATE TABLE "public".

### ISSUE THREAD

**Issue by maulikhdave9601672767** [lecaillon/Evolve#242]
42P07: relation "changelog" already exists Sql query: CREATE TABLE "public"."changelog" ( id SERIAL PRIMARY KEY NOT NULL, type SMALLINT, version VARCHA... 42P07: relation "changelog" already exists

i m using evolve i already 2 scripts

![image](https://user-images.githubusercontent.com/33731341/135621662-11e91772-7a25-4b82-9711-f0f8dfa4ba29.png)

and database i already have 

![image](https://user-images.githubusercontent.com/33731341/135621743-e0818a95-8f90-4269-94b9-5c29d16b2ead.png)

why i m getting issue after each new script adding inside my migration folder.

**Comment by lecaillon** [comment]
Please write an issue where I can reproduce this behavior. Thanks

**Comment by maulikhdave9601672767** [comment]
Ohh ok  :)
i  m using 3.1.0-alpha1.
i m using concept of sharding so i will have more then one database to do same operation  with evolve.

script content just sample table creation statment  and some table drop statment nothing fancy.

so when my application start it will give me list of database where my script will fire with evolve.

it can be 2 or more depend on configuration let me know if you need more information

**Comment by lecaillon** [comment]
The issue seems to me link to the sharding thing. Because your migration test is very standard and works on all my integration tests.
You will have to search by yourself because i cannot reproduce your conf on local.
What I can say to help is that `changelog` is the name of the table Evolve creates the first time it starts to log history of all migrations it executes.
What i can guess is that Evolve try to find the table with this [query](https://github.com/lecaillon/Evolve/blob/19a4ade04da2e6845ffe40c20c44b13a9662347a/src/Evolve/Dialect/PostgreSQL/PostgreSQLMetadataTable.cs#L35) and it returns false. Then Evolve wants to [create the table](https://github.com/lecaillon/Evolve/blob/19a4ade04da2e6845ffe40c20c44b13a9662347a/src/Evolve/Dialect/PostgreSQL/PostgreSQLMetadataTable.cs#L40) and fails because, i don't know how, it exists.
Maybe with your sharding configuration there is some things to take in account to know if a table exists...?
Keep me in touch if you find something

**Comment by lecaillon** [comment]
Issue closed because no update on it. If there is any news, feel free to open a new one and linked this one
