### ISSUE TITLE
SingleStore support

### ISSUE THREAD

**Issue by stefandevo** [lecaillon/Evolve#260]
Hi,
Would you accept a PR for SingleStore support? https://www.singlestore.com
It's basically a wire compatible database with MySql, but has some specific stuff that withholds the current MySql to work 100%.
I am happy to prepare a PR if you want.

I saw the 3.1 alpha commits where there is a namespace change; any idea if it would take some time before this gets live, or would I base the PR on the current 3.0 version?

**Comment by stefandevo** [comment]
If #263 is accepted, I can use this great library and implement SingleStore support myself outside of the library.

**Comment by lecaillon** [comment]
See my [response](https://github.com/lecaillon/Evolve/pull/263#issuecomment-1020639812). Sorry for the time you spend on this.
What you can do in your case, is to fork the repo I guess. The version in master is stable. In few days/weeks I will release Evolve 3.1.0. I am quite confident about the fact that if it works now for SingleStore, it will works a long time without any issues. The fact you use the Evolve class directly and not the CLI or the Tool is a good point too, because they can be tricky over the different version of the .NET SDK

Don't hesitate to post questions here, if you need help understanding some part of the code. Good luck

**Comment by stefandevo** [comment]
Is it ok that I publish my fork to Nuget with a clear indication that it is your project, all credits to you, but that the fork can be helpful if you want to implement your own dbms?

**Comment by lecaillon** [comment]
Yep no problem
