### ISSUE TITLE
Feature request: support Secrets Manager

### ISSUE THREAD

**Issue by jaketrent** [lecaillon/Evolve#54]
I can't tell if you support this or not... can one use the Secrets Manager to store the `Evolve.ConnectionString`?

As in:
https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?tabs=visual-studio

That would be great if it did.  Initial testing leads to believe this is not yet supported.

For instance, this command adds the secret:

```
dotnet user-secrets set ConnectionStrings:Evolve.ConnectionString "Host=localhost;Username=postgres;Password=postgres;Database=todo"
```

But when I run the app after removing `Evolve.ConnectionString` from `evolve.json`, I get "Value cannot be null" for "Parameter name: connectionString"

**Comment by gcelet** [comment]
I would love that feature too :)
I think right now it's not supported but i could be mistaken.
I manage to use Evolve and Secrets Manager if i put evolve configuration in appsettings.json directly and write some glue code to wire everything.
I made a quick gist to illustrate this idea here: https://gist.github.com/gcelet/ab12595ae5edfcddc3a092cc0f2cd006
Hope this help

Evolve is a great lib: thank for you work @lecaillon

**Comment by lecaillon** [comment]
Hi,

Thanks for your feedback and sorry for my (very) late response :)

Since the version 2.0, Evolve ships in 3 parts:
- Evolve
- Evolve.MSBuild
- Evolve.CLI

The use of configuration files like evolve.json is only supported in Evolve.MSBuild.
On Windows the Evolve.MSBuild package adds a task executed at build time, that under the wood, runs the Evolve.CLI (evolve.exe) with the correct arguments. Evolve is completly separated from your app.

Use secrets is tied to the `Configuration` api loaded from your app. Access a secret from another app (MSBuild in that case) would be very complicated if even possible.

So, I would say the only supported package that supports secrets is: [Evolve](https://www.nuget.org/packages/Evolve)
