### ISSUE TITLE
Running more than once the same script

### ISSUE THREAD

**Issue by adiefrat** [lecaillon/Evolve#58]
I'm running the script V1_1__CreateTestTable and then the script V1_2_InsertIntoTestTable. When I will run them again, it will fail because I already have the testTable in my db. When I run V1_2_InsertIntoTestTable script its running again even even though that in the changeLog table success = 1 and they both gets the same checksum value.
If I understand correctly whats written in the "Concepts" section :
"Once executed, the name and checksum of the migration are saved to a metadata table in your database. This table is checked every time Evolve is run, to see if the migration script has already been applied."
what i described above does not suppose to happen.

**Comment by lecaillon** [comment]
Hi @adiefrat Thx for the feedback

If you want me to help you, you'll have to give a lot more details about your issue. 
Because this test in Evolve checks that what you describe cannot happenned:
https://github.com/lecaillon/Evolve/blob/d6b7a1fd37e6db0f8db1806ba05c2a11a0c46265/test/Evolve.IntegrationTest.SQLServer/MigrationTest.cs#L51

So what version of Evolve do you use, what RDBMS and its version, how do you execute your migrations, what names because this one (V1_2_InsertIntoTestTable) has no extension and no separator (__) etc ...
The more the easier for me :)

**Comment by adiefrat** [comment]
Hey,
I'm using Evolve 1.8.0 with MSSQL(SQLServer) and .NET Framework 4.7.1. I set the migrations names with    
 <add key="Evolve.SqlMigrationSeparator" value="_" />
so the files names looks like this: V01_CreateTestTable, V02_InsertIntoTestTable.

This is the code I added to my Web.config:
    <add key="Evolve.ConnectionString" value="Server=.;Database=;Integrated Security=True;" />
    <add key="Evolve.Driver" value="SqlClient" />
    <add key="Evolve.Locations" value="C:\Project\CurrentProject\Sql_Scripts\" />
    <add key="Evolve.Command" value="migrate" />
    <add key="Evolve.SqlMigrationSeparator" value="_" />
    <add key="Evolve.EnableClusterMode" value="false" />

**Comment by lecaillon** [comment]
Try using the default separator please. Or anything but _

**Comment by adiefrat** [comment]
Tried that. Still the same. 
![image](https://user-images.githubusercontent.com/17640098/38667200-7db1c97c-3e49-11e8-9eb0-670b8775979d.png)

**Comment by lecaillon** [comment]
I see that the V02 script is executed multiple timples. But why not the V1 also ? strange.
Can you please change the 
add key="Evolve.Command" value="migrate" to 
add key="Evolve.Command" value="erase", execute and migrate again
And then test it again, because I see the sequence does not start to 1 (12 on your screenshot)

**Comment by lecaillon** [comment]
> I'm getting the same error when running it again after executing erase.

If Evolve erases or drops  your schema there shoud not be any error (at least the first time you execute your scripts)

**Comment by adiefrat** [comment]
So I created new database and it works.
One of the problems was that I didn't write the DB name in the Evolve connectionstring- solved.
The other problem is that if I have a table that belongs to "dbo" schema and was not created by Evolve, erase will not work with the next error:
" Cannot erase schema dbo. This schema was not empty when Evolve first started migrations."
But I want to run the migration on existing db and not on empty one.

**Comment by lecaillon** [comment]
Ok that is a good start :)
Using Evolve to automate sql migrations on an existing database is ok. 
The only thing is Evolve cannot erase schemas it has not previously created. And it is perfectly fine. It is the desire behaviour because if the schema was not empty when Evolve first started, it will not be able to rebuild it if it erases it.
So have you still got a problem ?

**Comment by adiefrat** [comment]
No.
Can you help me with issue #59 ?
