### ISSUE TITLE
A number of DBs at the same server on production

### ISSUE THREAD

**Issue by adiefrat** [lecaillon/Evolve#59]
I wanted to know if I could run the production on a different DBs(at the same server) dynamically and if so what do I need to change in the code so it will work?
Also, do I need to add the "In-app mode" code that was mention at the [getting started](https://evolve-db.netlify.com/getting-started/) section to my code? If so, where?

**Comment by lecaillon** [comment]
You have to change the connexion string between your env.
You can use environment variables to do so: #18

**Comment by antgel** [comment]
@lecaillon Thanks for the interesting answer. We'd like to ask more questions based on our use case (several databases, one representing general metadata, and the others representing customers, each of which has the same schema - not the same schema as the metadata).

Related to MSBuild vs in-app. It seems from your answer, that we need to loop over all of our databases, which looks like something that we can only do in-app. But the disadvantage is that migration errors won't be caught at build-time, and run-time is a bit late in the day, we wouldn't want our app not to come up because of a migration error. Is there a way to loop through several databases in the MSBuild mode?

If not, and we need to do it at runtime, we have the problems that:

* A migration failure can stop our app coming up (I guess we could catch the exception but still, it's late in the day.
* It can make application start slow.

We were thinking to add another project to our solution, which runs before we restart IIS. This project would solely be responsible for Evolve migrations, and if a migration failed, we could abort the deploy pipeline but at least our application wouldn't be affected.

Is this a sane plan, or is there a better way to do it?

**Comment by lecaillon** [comment]
At first, MSBuild mode was more a *dev mode*. More over you will not be able to loop over your DBs.
You could have one project by database/customler but i'm sure it seems akward.

So, indeed the best option should be the in-app mode. 
And if you want to run early, like you said, have a separate dedicated Evolve ConsoleApp that you run after a successfull build (in a MSBuild task of your main project for example). You will then have the same behaviour in dev than in CI.

We have plan to ship an Evolve CLI, but not so soon I think ...

Have you got more questions about this issue or can I close it ?
