### ISSUE TITLE
Support for already existing databases

### ISSUE THREAD

**Issue by chenmela** [lecaillon/Evolve#6]
Say I have a database updated to version 3 and want to begin using Evolve to migrate version 4 and onward. It is not currently possible without manipulating file names or moving old scripts to a different project folder. 

I would be interested in seeing functionality for Evolve to recognize certain scripts have already been executed, and to only migrate scripts after a particular version number. This could be accomplished with a config option to set version number, for example.

**Comment by lecaillon** [comment]
Hi @chenmela 

That is definitely a feature to add.

I can add a new _StartVersion_ parameter. 
During migration if this parameter is set, a new record (type=3) is inserted in the metadata table.
Evolve will then ignore all migrations until this version, excluded.

Note:
- Only one _StartVersion_ should be allowed by database; if not an exception is thrown.
- Because the database schema was not empty when Evolve first started, the `Erase` command sould not be allowed.

What do you think about it ?

**Comment by chenmela** [comment]
This sounds reasonable to me.

**Comment by lecaillon** [comment]
Done in version 1.3.0

See `StartVersion` parameter in https://github.com/lecaillon/Evolve/wiki/Configuration
