### ISSUE TITLE
depsFile required?

### ISSUE THREAD

**Issue by ben-foster-cko** [lecaillon/Evolve#61]
I'm initialising Evolve like so:

```
                   var evolve = new Evolve.Evolve("evolve.json") // retrieve the MSBuild configuration
                    {
                        Locations = new List<string> { "db/migrations" }, // exclude db/datasets from production environment
                        IsEraseDisabled = true, // ensure erase command is disabled in production
                    };
```

Contents of `evolve.json`:

```
{
  "Evolve.Driver": "SqlClient",
  "Evolve.ConnectionString": "data source=localhost;database=evolve;user id=user;password=xxx", // "Data Source=:memory:"
  "Evolve.Locations": "db",
  "Evolve.Command": "migrate",
  "Evolve.Placeholder.table4": "table_4"
}
```

When running I get the following exception:

```
System.ArgumentException: The string cannot be empty.
Parameter name: depsFile
   at Evolve.Utilities.Check.NotNullOrEmpty(String text, String parameterName)
   at Evolve.Connection.CoreDriverConnectionProviderBase..ctor(String driverName, String connectionString, String depsFile, String nugetPackageDir, String msBuildExtensionsPath)
   at Evolve.Evolve.GetConnectionProvider()
   at Evolve.Evolve.InitiateDatabaseConnection()
   at Evolve.Evolve.InternalExecuteCommand(Action`1 commandAction)
```

It looks like the correct constructor is being called and looking through the Evolve source I can't see why `depsFile` is required.

**Comment by lecaillon** [comment]
Well... while it's possible to use this constructor from a .Net Core project, it was not meant to be used that way :) This constructor is dedicated to the MsBuild mode, not the in-app mode.
I should definitly change that in a future release.

So several solutions for you:
  - If you want to mix configuration by code and json file, provide a SqlConnection in the constructor (and a log delegate by the way even if this one is really optional ;) )
  - Otherwise only use the in-app mode and don't provide a json configuration file. You still have to provide a SqlConnection: 
```
public Evolve(IDbConnection dbConnection = null, Action<string> logInfoDelegate = null)
```

Is it ok for you ?

**Comment by ben-foster-cko** [comment]
That's fine. I would definitely avoid using optional parameters if they are not optional. Thanks for the help.
