### ISSUE TITLE
Revisit the sp_releaseapplock for SQL Server connections

### ISSUE THREAD

**Issue by PratimNag** [lecaillon/Evolve#97]
Evolve migrate with SQL Server throws the following error during build and run time:

Cannot release the application lock (Database Principal: 'public', Resource: 'Evolve') because it is not currently held. Sql query: sp_releaseapplock Cannot release the application lock (Database Principal: 'public', Resource: 'Evolve') because it is not currently held.
   at Evolve.WrappedConnectionEx.Execute[T](WrappedConnection wrappedConnection, String sql, Func`2 query, Action`1 setupDbCommand)
   at Evolve.WrappedConnectionEx.ExecuteDbCommand[T](WrappedConnection wrappedConnection, String sql, Action`1 setupDbCommand, Func`2 query)
   at Evolve.Dialect.SQLServer.SQLServerDatabase.ReleaseApplicationLock()
   at Evolve.Evolve.InternalExecuteCommand(Action`1 commandAction)
   at Evolve.Evolve.Migrate()
   at Evolve.Evolve.ExecuteCommand()
   at Evolve.MsBuild.EvolveBoot.Execute()

This is happening in SQL Server 2012

**Comment by lecaillon** [comment]
Can you give me more insights please:
- what version of the framework do you use ? 
- which mode of Evolve do you use (in-app or MSBuild mode) ?
- what are the migration scripts you execute, and is it happens always even when you run only one little migration (for testing) ?

More over, to fix your issue, if there is only one application that can executes Evolve at a time, (when there is not multiple instances of your app running in a cluster for example) you can use the option `Evolve.EnableClusterMode=false` to disable session level lock that appears to cause your issue.

**Comment by PratimNag** [comment]
Here are the details:

* what version of the framework do you use ? - >Evolve 1.9.0 with .NET Core 2.1
* which mode of Evolve do you use (in-app or MSBuild mode) ? in-app
* what are the migration scripts you execute, and is it happens always even when you run only one little migration (for testing) ? -- Create dB, Create Table. Yes. It is happening always.

**Comment by lecaillon** [comment]
Can you post your Create table migration script in order for me to reproduce the issue ? Because Evolve comes with a lot a tests and this simple test is obiously part of it.

FWI Create DB is not supported in Evolve. So do not try to execute a script with those DDL statements.
https://evolve-db.netlify.com/requirements/sqlserver/

**Comment by lecaillon** [comment]
No news, good news. If not, please re-open the issue

**Comment by Obish** [comment]
hi

Thanks for your prompt answers but i'm having same issue .

Please see my migration script

USE ${databasename}
GO


-- =============================================
-- Author:		<Author,,Inioluwa Obisakin>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[proc_tblTransactions_AddTransaction]
    @mert_id Bigint,
	@transaction_ref nvarchar(250),
	@preffered_channel nvarchar(50),
	@transaction_amount decimal,
	@transaction_currency_id int,
	@access_token nvarchar(100),



AS
BEGIN
DECLARE @ResponseCode varchar(50), @id varchar(50), @ResponseDescription varchar(max) ,@@Exist VARCHAR(10) ;

SET @@Exist = (SELECT COUNT(1) FROM Transactions WHERE transaction_ref = @transaction_ref and mert_id = @mert_id)

	
	IF @@Exist > 0
	 begin
      SET @ResponseCode = 2;
				SET @id = null;
				SET @ResponseDescription = 'Duplicate Ref';
				EXEC dbo.ReturnMessage @ResponseCode, @id, @ResponseDescription;

      return
	  end
	ELSE
	BEGIN TRANSACTION
		BEGIN TRY
			SET NOCOUNT ON;
			
    
				INSERT INTO ${databasename}.[dbo].[Transactions]
					   (
        [mert_id]
      ,[transaction_ref]
      ,[preffered_channel]
      ,[transaction_amount]
      ,[transaction_charges]
      ,[transaction_currency_id]
      ,[access_token]
      ,[bearer]
      ,[created_at]
					   )
				 VALUES
					   (@mert_id
					   ,@transaction_ref
					   ,@preffered_channel
					   ,@transaction_amount
					   ,null
					   ,@transaction_currency_id
					   ,@access_token
					   ,null
					   ,GETDATE()
					   )


					   if(@@ROWCOUNT > 0)
					   begin
					   SET @ResponseCode = 1;
					   end
					   else
					   begin 
					   SET @ResponseCode = 0;
					   end

   	COMMIT TRANSACTION;
			SET @ResponseCode = @ResponseCode;
			set @id = @@IDENTITY
			SET @ResponseDescription = 'Success';
   END TRY
		BEGIN CATCH
			
				ROLLBACK TRANSACTION;
				SET @ResponseCode = 0;
				SET @id = ERROR_NUMBER();
				SET @ResponseDescription = ERROR_MESSAGE();
			
		END CATCH

		EXEC dbo.ReturnMessage @ResponseCode, @id, @ResponseDescription;
END

**Comment by lecaillon** [comment]
Your post is not well formatted. It is hatrd to understand what you want to achieve.

**Comment by sergiu-svinarciuc** [comment]
Hey @lecaillon , first of all thank you so much for a great tool!

The root cause of the issues above, most probably, is the usage of "use [<db>]" statement, specifically when this one is not consistent with the target DB provided in the connection string. In such case, when Evolve is done with applying the patches, it tries to release the lock in a different context because of the "use" statement. 

There is also a nasty side effect. Evolve reports that the patches have been applied successfully, when actually none of the patches coming after the one with an inconsistent "use" statement are applied.

Besides fixing the misleading message about patches being successfully applied when they are actually not, would it make sense to add a safety-net and fail the migration if the patch contains a "use" statement? We might also want to add this to the list of limitations?

Happy to contribute in any ways, let me know your thoughts.

**Comment by lecaillon** [comment]
Thanks a lot @sergiu-svinarciuc ! That's a serious lead. I think you're right. And it explains why my current SQL Server tests work, because I do not change of database in my scripts [V3_1](https://github.com/lecaillon/Evolve/blob/master/test/Evolve.Tests/Integration/SQLServer/Resources/Sql_Scripts/Migration/V3_1__create_database_evolvedb.sql) and [V_3_1_1](https://github.com/lecaillon/Evolve/blob/master/test/Evolve.Tests/Integration/SQLServer/Resources/Sql_Scripts/Migration/V3_1_1__create_table_evolve.sql). I use the fully qualified table name to create and insert data in the new created database.

I will investigate in next days what we can do about it. And again your proposal seems legit. I just want to try to change database in a migration configured with the option : `EnableClusterMode = false`
Consequenses will be no node synchronization at migration time (no database lock). But for some scenario it won't be an issue.

I'll keep you in touch Sergiu. Thanks again

**Comment by sergiu-svinarciuc** [comment]
Sounds great @lecaillon and thank you for a quick turnaround on this one.

**Comment by lecaillon** [comment]
@sergiu-svinarciuc I finally reproduce the issue. As Sergiu thought it is link to the `USE [database]` statement. When it is used in a script, SQL Server changes session from where the Evolve application lock is attached, causing a release of the lock. Then it fails when Evolve tries to release it again at the end of the migration.
To avoid this pitfall, several options:
- Do not use the `USE [mydb]` statement in your script. Prefer the fully qualified name of the database object : `mydb.dbo.table1`
- Set the Evolve option `EnableClusterMode` to `false`. This option prevents two distinct Evolve executions from executing an Evolve command on the same database at the same time, by using a session lock (`sp_getapplock`). **If you don't need it**, either because you run Evolve manually with the CLI or the Tool, or because you only have 1 instance of your app running Evolve at the same time, you can set it to false safely.

I will update the Evolve documentation about it by the release of Evolve 3.0.0
